### ISSUE TITLE
Replace path add-on

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/jumeaux#134]
```
one:
  url: http://hoge1
other:
  url: http//hoge2
```

`requests`
```
/path/pop/push
```

expected (for example)

```
one: http//hoge1/path/pop/push
other: http//hoge2/path/pop/posh (replace: push => posh)
```
