### ISSUE TITLE
res2res/json add-on

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/jumeaux#90]
It enables to transform from anything(bytes) to json(str) as long as specifing package and transform function.

Configulation seems to as following.

```yaml
res2res:
  - name: json
    config:
      transformer:
        module: str2json
```

and implements `transform` function in `str2json` package as following

```
def transform(anything: bytes, encoding: str) -> str:
    # implementations....
    return json
```
